DEV-4456: Accept TimeoutError in state match
siklu/ci-automation pull request #23
Opened 2022-02-02 12:54 UTC by linaza-siklu

DEV-4456: Accept TimeoutError in state match:
Handling TimeoutError exception after timeout pass to accept or not accept TimeoutError and move to next_state or raise the TimeoutError.  
- Added boolean attribute "capture_timeout" to the TopLevelModel Match, the attribute is False by default.
- Handle timeout match in the device_model.py
- Added unit tests to input_test.py to test timeout match and pattern unique values.
- changed matches patterns to be unique value.
- Accept TimeoutError only by one match

2022-02-08 11:51 UTC, linaza-siklu commented on setup_script/DeviceSetup.py
> +        regex_matches_timeout = [match.timeout_capture for match in input_model.matches]
@shmuelhazan added it to the pydantic model, please see next commit

2022-02-08 12:58 UTC, shmuelhazan commented on setup_script/DeviceSetup.py
> +                # capture timeout and return match to the next_state
Can you add a more detailed comment?

2022-02-08 12:59 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +            regex_matches_timeout.count(True) > 1
Are you sure that this will throw ValidationError?

2022-02-08 13:27 UTC, linaza-siklu commented on setup_script/models/pydantic/device_model.py
> +            regex_matches_timeout.count(True) > 1
Yes

2022-02-08 13:29 UTC, berezhinskiy commented
@shmuelhazan @linaza-siklu Hi, I have enabled Jenkins PR job for this repo. Please rebase from the master.

2022-02-08 14:11 UTC, linaza-siklu commented on setup_script/DeviceSetup.py
> +                # capture timeout and return match to the next_state
okay

2022-02-10 08:31 UTC, linaza-siklu commented
> @shmuelhazan @linaza-siklu Hi, I have enabled Jenkins PR job for this repo. Please rebase from the master.

Done.

2022-02-10 08:56 UTC, shmuelhazan requested changes

2022-02-10 08:56 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +            regex_matches_timeout.count(True) > 1
Can you explain how it will do so?

2022-02-10 08:56 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +            assert self.device_setup._process_input(input_model) == input_model.matches[1]
How will that work? input_model.mathces[1] does not exists.

2022-02-10 08:56 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +            assert self.device_setup._process_input(input_model) == input_model.matches[1]
If I understand correctly, pyexpect won't raise AssertionError in this case. We are capturing this statement's failure.

2022-02-10 08:58 UTC, shmuelhazan commented
If I understand correctly, we are missing unit-tests for validating that there is only one capture_timeput match.

2022-02-13 08:46 UTC, shmuelhazan commented on setup_script/DeviceSetup.py
> +            if input_model.matches is not None:
is it valid for matches to be none?

2022-02-13 08:47 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +            raise ValidationError
Currently, you are raising a class object. Can you please use `ValidationError("explain the error here")`.

2022-02-13 09:03 UTC, linaza-siklu commented on setup_script/models/pydantic/device_model.py
> +            raise ValidationError
this does not work using ValidationError, instead i used TypeError

2022-02-13 09:12 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +            assert self.device_setup._process_input(input_model) == input_model.matches[1]
changed it in the next commit

2022-02-16 13:00 UTC, shmuelhazan requested changes

2022-02-16 13:00 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +    def test_process_input_timeout_validation(self, mock_read: Mock):
it is unclear for me what this test does (as opposed to other tests)

2022-02-17 06:56 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +    def test_process_input_no_match_no_timeout_string(self, mock_read: Mock):
i will remove the second, not sure why i added it but they test the same issue

2022-02-17 06:59 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +            assert self.device_setup._process_input(input_model) == input_model.matches[1]
fixed it in the next commit

2022-02-17 07:02 UTC, linaza-siklu commented on setup_script/DeviceSetup.py
> +            if input_model.matches is not None:
No it is not valid for matches to be None, matches can only be list of match 
this line was removed

2022-02-17 07:06 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +    def test_process_input_timeout_validation(self, mock_read: Mock):
see next commit

2022-02-17 09:30 UTC, shmuelhazan requested changes

2022-02-17 09:30 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +        if regex_matches_timeout.count(True) <= 1:
can you please flip the condition? (e.g. exit on error condition first, and later continiue)

2022-02-17 09:30 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +                    raise pydantic.ValidationError
Can you add text in the error?

2022-02-17 09:30 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +            Check that matches pattern are unique for each machine state
Is this description correct?

2022-02-17 09:30 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +        """
I don't understand what is being tested here. If there won't be an exception here, would the test fail?

2022-02-17 10:07 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +        """
this test tests that match pattern is unique, here two patterns are equals to 'Login1', so i tested if a validation error is raised in this case, which is what is expected
exception is raised from Validatore in device_model.py

2022-02-17 10:08 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +            Check that matches pattern are unique for each machine state
Check that matches patterns are unique for current state machine

2022-02-17 12:09 UTC, shmuelhazan requested changes

2022-02-17 12:09 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +            assert self.device_setup._process_input(input_model)
process_input will throw here. I don't understand why do we need to assert on its return value.

2022-02-17 12:09 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +        """
@linaza-siklu Will the test fail if the validation won't be correct?

2022-02-17 12:09 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +        try:
same here. That won't fail in case the code won't throw.

2022-02-17 12:28 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +        """
yes, if the the input model has two patterns that are the same then the test fails
the validation error is thrown only after reading the yaml file

2022-02-17 12:31 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +            assert self.device_setup._process_input(input_model)
my mistake, no need for assert , only call process_input

2022-02-17 12:51 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +        try:
these two tests will fail only if you change input_model, i only added them to test that ValidationError is raised in two cases:
- case 1: two or more matches accepts TimeoutError
- case 2: two or more matches patterns are identical 
They won't fail unless you change the device_model.py (pydantic model)
i don't understand why this is confusing.

2022-02-20 13:28 UTC, shmuelhazan requested changes

2022-02-20 13:28 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +        mock_read.assert_not_called()
do we need these lines?

2022-02-20 13:28 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +        mock_read.assert_not_called()
do we need these lines?

2022-02-20 13:30 UTC, linaza-siklu commented on setup_script/unit-tests/input_test.py
> +        mock_read.assert_not_called()
No, this is only to make sure functions are not called when Input model isn't valid, do you want me to remove these calls?

2022-02-20 13:40 UTC, shmuelhazan commented on setup_script/unit-tests/input_test.py
> +        mock_read.assert_not_called()
I think that it is better to have the least amount of code in the unit-tests

2022-02-21 07:39 UTC, shmuelhazan approved these changes

2022-02-21 07:48 UTC, merged