DEV-4638: make action wait before sending output to device
siklu/ci-automation pull request #38
Opened 2022-04-19 08:14 UTC by linaza-siklu

This pull request changes the 
Change state actions, action type to be Output or Wait, 
if action is Wait then the script sleeps for "wait" seconds,
and in the action is Output the script sends output to device.

2022-04-19 09:19 UTC, shmuelhazan requested changes

2022-04-19 09:19 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +    pattern: Optional[str]
why is it optional?

2022-04-19 09:19 UTC, shmuelhazan commented on setup_script/unit-tests/actions_test.py
> +        actions = [Wait(wait=5), Output(output=["1", "2"]), Output(output="3")]
that does not check that wait is being called. Maybe need to mock time.sleep.

2022-04-19 09:21 UTC, linaza-siklu commented on setup_script/unit-tests/actions_test.py
> +        actions = [Wait(wait=5), Output(output=["1", "2"]), Output(output="3")]
okay

2022-04-19 09:21 UTC, linaza-siklu commented on setup_script/models/pydantic/device_model.py
> +    actions: Actions  = list()
will fix it

2022-04-19 09:22 UTC, linaza-siklu commented on setup_script/models/pydantic/device_model.py
> +    pattern: Optional[str]
no need for optional here, will change it

2022-04-19 10:55 UTC, shmuelhazan requested changes

2022-04-19 10:55 UTC, shmuelhazan commented on setup_script/DeviceSetup.py
> +                time.sleep(action.wait)
maybe better to add process_wait as we do in process_output?

2022-04-19 10:55 UTC, shmuelhazan commented on setup_script/unit-tests/actions_test.py
> +def check_number_of_calls_to_write(mock_write: Mock, mock_sleep: Mock, actions: Actions):
the name of the function is check_number_of_calls_to_write. I don't think it is applicable to add sleep here.

2022-04-19 10:55 UTC, shmuelhazan commented on setup_script/unit-tests/actions_test.py
> +        with patch('interfaces.AbstractDeviceIO.AbstractDeviceIO.write') as mock_write:
why not patch('interfaces.AbstractDeviceIO.AbstractDeviceIO.write')?

2022-04-19 10:59 UTC, linaza-siklu commented on setup_script/unit-tests/actions_test.py
> +def check_number_of_calls_to_write(mock_write: Mock, mock_sleep: Mock, actions: Actions):
Do you want me to rename it or create another function to test number of calls to sleep function?

2022-04-19 12:34 UTC, shmuelhazan commented on setup_script/DeviceSetup.py
> +            self.logger.info(f"Sleep for: \"{output_model.wait}\" seconds")
```suggestion
            self.logger.info(f"Sleeping for: \"{output_model.wait}\" seconds")
```

2022-04-19 12:35 UTC, shmuelhazan requested changes

2022-04-19 18:40 UTC, linaza-siklu commented on setup_script/unit-tests/actions_test.py
> +def check_number_of_calls_to_write(mock_write: Mock, mock_wait: Mock, actions: Actions):
i will remove mock_wait from the check_number_of_calls_to_write function in the next commit

2022-04-20 06:40 UTC, dima1308 commented on setup_script/DeviceSetup.py
> +                self._process_wait(action)
Instead of checking for different types of actions, maybe it is better to have a function into the Action class that will execute the action (wait or do output)?

2022-04-20 06:47 UTC, linaza-siklu commented on setup_script/DeviceSetup.py
> +                self._process_wait(action)
This is what we had before and @shmuelhazan suggested to add another function that processes wait, also this way it is better for testing we simply test if  _process_wait was called in process_actions in order to validate number of calls with wait , same for output, we test how many times _process_output was called in the _process_actions function

2022-04-20 06:53 UTC, dima1308 commented on setup_script/DeviceSetup.py
> +                self._process_wait(action)
If @shmuelhazan approve it, fine.
From my point of view, it looks like a patch.
About testing - you can do the same logic if Action class will execute the action. For that, you need to mock the function that execute action.

2022-04-24 06:41 UTC, shmuelhazan commented on setup_script/DeviceSetup.py
> +                self._process_wait(action)
@dima1308 Action is not a regular class with member function but rather a dataclass (object representation of the json file). Therefore, we have to handle its actions from the outside.

2022-04-24 06:43 UTC, dima1308 commented on setup_script/DeviceSetup.py
> +                self._process_wait(action)
@shmuelhazan I understand that. However, maybe it is better to turn action class to the class that execute the real action?

2022-04-24 06:49 UTC, shmuelhazan commented on setup_script/DeviceSetup.py
> +                self._process_wait(action)
@dima1308 You are correct. This is a code smell. @linaza-siklu Maybe we need to add a virtual `perform_action` to a new class `AbstractAction` and then implement it in all actions.

2022-04-25 11:28 UTC, dima1308 commented on setup_script/PerformAction.py
> +        if isinstance(action, Wait):
better to use derived class per action type.

2022-04-25 11:28 UTC, dima1308 commented on setup_script/interfaces/AbstractAction.py
> +    def _sleeping_time(self, wait):
why do we need this function? If in the future we will implement 10 additional actions, we don't want to add 10 empty functions there.

2022-04-28 11:23 UTC, shmuelhazan requested changes

2022-04-28 11:23 UTC, shmuelhazan commented on setup_script/DeviceSetup.py
> +from models.pydantic.device_model import Actions, Match, Input, State, Output,  ErrorState, FinalState
do we need this change?

2022-04-28 11:23 UTC, shmuelhazan commented on setup_script/DeviceSetup.py
> +            action.perform_action(action, self)
why do we need to give it ourselves?

2022-04-28 11:23 UTC, shmuelhazan commented on setup_script/interfaces/AbstractDeviceIO.py
> +    def read_expect_regex(self, list_of_regex: List[str], timeout: int) -> Tuple[str, dict]:
These changes are incorrect (probably added by mistake)

2022-04-28 11:23 UTC, shmuelhazan commented on setup_script/interfaces/AbstractDeviceSetup.py
> -
needed?

2022-04-28 11:23 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +from models.pydantic.interfaces.AbstractAction import AbstractAction
why have two interfaces directories? instead maybe better to move deivce_model out and have a common interfaces directory.

2022-04-28 11:23 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +        device_setup._process_output(action)
maybe better to move the output implementation here.

2022-04-28 11:23 UTC, shmuelhazan commented on setup_script/models/pydantic/interfaces/AbstractAction.py
> +    def perform_action(self, action, device_setup):
unclear why we need the action here. We already have self. Additionally, we should not need device_setup.

2022-04-28 11:23 UTC, shmuelhazan commented on setup_script/models/pydantic/interfaces/AbstractAction.py
> +        pass
should raise NotImplementedError.

2022-04-28 12:17 UTC, linaza-siklu commented on setup_script/models/pydantic/device_model.py
> +        device_setup._process_output(action)
You mean removing _process_output from "DeviceSetup" and implement it here?

2022-04-28 13:01 UTC, shmuelhazan commented on setup_script/models/pydantic/interfaces/AbstractAction.py
> +    def perform_action(self, action, device_setup):
because it is incorrect. DeviceSetup is a high-level class. Simple actions should not know about it. If we need device_io there, we should give it specifically.

2022-04-28 13:01 UTC, shmuelhazan commented on setup_script/models/pydantic/device_model.py
> +        device_setup._process_output(action)
yes

2022-04-28 13:28 UTC, shmuelhazan commented on setup_script/device_model.py
> +            device_io.write(string)
any reason to have two functions?

2022-05-01 07:25 UTC, shmuelhazan approved these changes

2022-05-01 07:42 UTC, merged