Dev 4597 add scp to state machine action
siklu/ci-automation pull request #43
Opened 2022-05-15 10:08 UTC by linaza-siklu

** Description **
This pull request adds a new state machine action type "scp", uses scpClient to upload files to TG device.

** Tests ** 
Tested code on EH8010 device , managed load files to device successfully
Fixed unit tests

** Jira Issue **
DEV-4597

2022-05-15 10:40 UTC, shmuelhazan requested changes

2022-05-15 10:40 UTC, shmuelhazan commented on setup_script/device_model.py
> +class Info(BaseModel):
maybe it needs to be a class inside of SCP?

2022-05-15 10:40 UTC, shmuelhazan commented on setup_script/device_model.py
> +    destination: str
we don't want to be able to use variables on any of these?

2022-05-15 10:40 UTC, shmuelhazan commented on setup_script/unit-tests/actions_test.py
> +                with patch('device_model.SCP.perform_action') as mock_perform_scp:
maybe better to only test scp? (instead of testing all of these?)

2022-05-15 10:40 UTC, shmuelhazan commented on setup_script/unit-tests/actions_test.py
> +                    assert mock_perform_scp.call_count == 1
maybe better to mock paramiko's functions to make sure they are being called with the right parameters?

2022-05-15 10:47 UTC, linaza-siklu commented on setup_script/device_model.py
> +class Info(BaseModel):
okay

2022-05-15 10:50 UTC, linaza-siklu commented on setup_script/device_model.py
> +    destination: str
what do you mean? 
These values should be defined in the variables if we are using scp machine state acrion

2022-05-15 11:58 UTC, shmuelhazan requested changes

2022-05-15 11:58 UTC, shmuelhazan commented on setup_script/unit-tests/actions_test.py
> +                mock_paramiko_connect.assert_called_with('server', username='user', password='password', port=22)
maybe need to also check other functions (put, etc)

2022-05-15 12:46 UTC, linaza-siklu commented
@berezhinskiy can you please add "paramiko" to the docker for the CI automation, This PR fails because we are missing the "paramiko" python library
Thanks

2022-05-16 08:27 UTC, berezhinskiy commented
@linaza-siklu https://github.com/siklu/ci-infrastructure/pull/34 is not merged yet. Please, wait until new docker images will be pushed.

2022-05-16 09:12 UTC, berezhinskiy commented
@linaza-siklu paramiko was imported successfully, now build failed with different reason.

2022-05-16 09:16 UTC, linaza-siklu commented
@berezhinskiy can you please add python "scp" library also 
Name: scp
Version: 0.14.4
Summary: scp module for paramiko
Home-page: https://github.com/jbardin/scp.py

2022-05-17 08:01 UTC, shmuelhazan requested changes

2022-05-17 08:01 UTC, shmuelhazan commented on setup_script/unit-tests/actions_test.py
> +                                        'path': 'path', 'destination': 'destination'})]
maybe better to also test variables here.

2022-05-17 11:04 UTC, shmuelhazan approved these changes

2022-05-17 11:06 UTC, merged