DEV-4791: Bidirectional SCP support
siklu/ci-automation pull request #54
Opened 2022-06-13 07:48 UTC by eduardpo

## Description
We need to support bidirectional SCP in order to copy tech files from 8010 device

## Tests
actions_test

## References
JIRA: DEV-4791

2022-06-13 07:49 UTC, shmuelhazan approved these changes

2022-06-19 09:06 UTC, shmuelhazan requested changes

2022-06-19 09:06 UTC, shmuelhazan commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la /var/sw/etc/\n"
is that correct?

2022-06-19 09:06 UTC, shmuelhazan commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +        - pattern: '[\s\S]+'
what are we doing here?

2022-06-19 09:16 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la /var/sw/etc/\n"
yes, please notice TODO section 5 lines below:
#TODO: transfer verification by preserved timestamp

2022-06-19 09:22 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +        - pattern: '[\s\S]+'
expecting any input from device,
will be changed later, after verification will be checked by preserved timestamp...

2022-06-19 09:31 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la /var/sw/etc/\n"
maybe we need to add some assert mechanism to make sure that the file is actually transferred to the device. If not transferred, the setup script should go to the `ErrorState`

2022-06-19 09:33 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +        - pattern: '[\s\S]+'
why check for timestamp? The file should be never overridden. Probably we need to check that file does not exist initially and exists after the operation.

2022-06-19 10:17 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la /var/sw/etc/\n"
providing the files should be never overridden, its existence before and after is the most reliable check imho

2022-06-19 10:22 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la /var/sw/etc/\n"
and maybe, most safest is to remove, and check its existence after?
and btw, what's the rational of never override ..?

2022-06-21 08:58 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +        #TODO: transfer verification by preserved timestamp
why do we need to validate the transfer? why it is not enough to rely on the SCP return code?

2022-06-21 08:58 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010.yaml
> +      - output: "reboot"
`reboot` or `reboot -f`?

2022-06-21 08:58 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010.yaml
> +      - output: "set ip 1 ip-addr {device_ip} prefix-len 24"
we need to use a parameter instead of hard-coded `prefix-len`. To do it, we need to merge https://github.com/siklu/jenkinslibrary/pull/140/ first

2022-06-21 08:58 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010.yaml
> +      - output: "setenv bootargs loglevel=0"
@shmuelhazan as I remember, you told me we don't need this command.
Instead, we need to configure the log level in u-boot params.
Can you please send me the command on how to do it on u-boot?

2022-06-21 10:38 UTC, dima1308 commented on setup_script/PexpectDeviceIO.py
> -        self._session.write(output)
why do we need this change?

2022-06-21 11:19 UTC, eduardpo commented on setup_script/PexpectDeviceIO.py
> -        self._session.write(output)
write does not return anything, and we have always append trailing '\n' to output we send in yaml...

2022-06-21 11:22 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010.yaml
> +      - output: "reboot"
what do you mean?

2022-06-21 11:38 UTC, shmuelhazan commented on setup_script/PexpectDeviceIO.py
> -        self._session.write(output)
@eduardpo What will happen if the user wants to send something without \n at the end?

2022-06-21 12:13 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010.yaml
> +      - output: "reboot"
why not use `reboot -f` as we do for other places?

2022-06-21 12:17 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010.yaml
> +      - output: "setenv bootargs loglevel=0"
> This is done on another task. In u-boot, need to do the same command but `env save` afterwards

do you know which command?

2022-06-21 12:46 UTC, eduardpo commented on setup_script/PexpectDeviceIO.py
> -        self._session.write(output)
reverted back.

2022-06-21 14:34 UTC, shmuelhazan commented on setup_script/device_model.py
> +        direction: str
```suggestion
        direction: DataTransferDirection
```

2022-06-21 15:02 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010.yaml
> +      - output: "reboot"
yes, let's do `reboot -f` here

2022-06-22 07:44 UTC, eduardpo commented on setup_script/device_model.py
> +        direction: str
Shmuel,
I thought it was a mistake, because our pydantic api supports only string and int, that's why i've changed..
am i wrong?

2022-06-22 07:54 UTC, shmuelhazan commented on setup_script/device_model.py
> +        direction: str
what do you mean by "our pydantic api"? pydantic support parsing of enums too.

2022-06-22 07:56 UTC, eduardpo commented on setup_script/device_model.py
> +        direction: str
i mean our Argument validation class

2022-06-22 13:19 UTC, shmuelhazan approved these changes

2022-06-22 14:17 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la {data_destination}\n"
Current implementation is not capturing its output in any case, and does not support such an `output action` "out of the box", so I suggest to add this as leftover to the next task of `rm -rf  ~/.ssh/known_hosts`

2022-06-22 14:24 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la {data_destination}\n"
the ls command will simply fail if you will use data_destination that does not exist on a device. How do you want to leave it?
BTW, how it is related to the next task of `rm -rf ~/.ssh/known_hosts`? For this task, you don't need to touch the YAML file at all.

2022-06-22 14:53 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la {data_destination}\n"
> the ls command will simply fail if you will use data_destination that does not exist on a device. How do you want to leave it? BTW, how it is related to the next task of `rm -rf ~/.ssh/known_hosts`? For this task, you don't need to touch the YAML file at all.

No it won't fail ,  checked it...
Regarding the future task, yes I would have done it on the same yaml context as I think it's a good option to have such a functionality,
But in case you prefer doing it in different way, please add it to your workaround suggestion:
https://jira-siklu.atlassian.net/browse/DEV-4822
Btw, we can simply add it to portfolio TestConfig.yaml before coping techfiles:
pc:
      orderedCommands:
        - /bin/bash -c 'set -o pipefail && rm -rf ~/.ssh/known_hosts

2022-06-22 15:01 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la {data_destination}\n"
> No it won't fail , I checked it...

I so, I don't understand why. Can you please explain?
In any case, I also don't understand how it is related to the future task?

> `- /bin/bash -c 'set -o pipefail && rm -rf ~/.ssh/known_hosts`

This will work. However SSH clients support the ability to configure known hosts behavior. We need to use it.

2022-06-22 17:46 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +definitions:
I don't understand what this YAML file does?
from the PR description, I understand that we are going to run `technician_file.sh` to collect logs. But I don't see where we are running this script? If we are going to collect logs, the name of this file `portfolio-eh8010-data-transfer.yaml` should be changed to something like `portfolio-eh8010-collect_logs.yaml`. Also, it is not clear to me why do we need to configure the direction of the file transfer? For logs collection, the direction is only from the device to the PC. Am I missing something?

2022-06-22 17:46 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +        # If in shell - reboot
if you are in the shell, why reboot? you can run the tech file collection script, copy the resulting archive, and exit.
it looks like we need to review and simplify the YAML state machine logic again.

2022-06-23 05:35 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +definitions:
Please refer to modified task description.

2022-06-23 05:53 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la {data_destination}\n"
>If so, I don't understand why. Can you please explain?
In any case, I also don't understand how it is related to the future task?

It won't fail because it's legal to send any output to device, pexpect spawn itself does not check the response, and as long as its child is alive it will work.

>This will work. However, SSH clients support the ability to configure known hosts behavior. We need to use it.

So, your suggested work around is not relevant anymore?
Please elaborate...

2022-06-23 06:15 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +        # If in shell - reboot
No I can't,
In order to be able to ssh/scp to device, setup_script must always get to the prompt through debug login, but the current initial prompt origin is always unknown, so you have to reboot->login as admin -> run debug login...
The original 8010 yaml which i've used as a template also counts on this behaviour.
I couldn't consider or report it as a bug, as I did not believe it might pass unnoticed...

2022-06-23 06:16 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +          next_state: *SetIPAddress
Please refer to modified description

2022-06-23 06:49 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +definitions:
@eduardpo if this task is only to support bidirectional SCP, you don't need to commit this YAML at all (this YAML is useless for production needs).

2022-06-23 06:58 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +        # If in shell - reboot
Let's go back to the tasks reqirements. If the reqirements is only to support bidirectional scp command, this yaml is not relevant at all and should not be committed.
If you are going to support copy logs from the device, you don't need to scp to device (as you mentioned)

2022-06-23 06:59 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +          next_state: *SetIPAddress
See my comments above

2022-06-23 07:51 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +        # If in shell - reboot
@shmuelhazan

2022-06-23 07:51 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +definitions:
@shmuelhazan

2022-06-23 07:52 UTC, eduardpo commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la {data_destination}\n"
@shmuelhazan

2022-06-23 08:39 UTC, dima1308 commented on setup_script/devices/portfolio-eh8010-data-transfer.yaml
> +      - output: "ls -la {data_destination}\n"
@eduardpo let's discuss it verbally - the discussion is too long for the PR.

2022-06-23 09:38 UTC, shmuelhazan commented
Let's add this PR without the YAML, then, in https://jira-siklu.atlassian.net/browse/DEV-4751, we will need to generate a tech file and collect it from a yaml file.

2022-06-23 09:41 UTC, eduardpo commented
> Let's add this PR without the YAML, then, in https://jira-siklu.atlassian.net/browse/DEV-4751, we will need to generate a tech file and collect it from a yaml file.

So, tech generation will be also done in the YAML context?

2022-06-23 09:43 UTC, shmuelhazan commented
> > Let's add this PR without the YAML, then, in https://jira-siklu.atlassian.net/browse/DEV-4751, we will need to generate a tech file and collect it from a yaml file.
> 
> So, tech generation will be also done in the YAML context?

I think. Otherwise, who will generate the tech file?

2022-06-23 09:46 UTC, eduardpo commented
> > > Let's add this PR without the YAML, then, in https://jira-siklu.atlassian.net/browse/DEV-4751, we will need to generate a tech file and collect it from a yaml file.
> > 
> > 
> > So, tech generation will be also done in the YAML context?
> 
> I think. Otherwise, who will generate the tech file?

Just making sure,
I'm updating the task description then, and will ask your approval soon, is it ok?

2022-06-23 13:54 UTC, shmuelhazan approved these changes

2022-06-23 15:36 UTC, merged